### PR TITLE
Change font-weight for class and tag

### PR DESCRIPTION
**Pull request by EQuimper**
Add font-weight for get the same style of the screenshot you provide. Look nicer and easy to read.

### CODE REVIEW

**Comment by sliepie** [comment]
I have pushed a new update to atom, with these changes

**Comment by EQuimper** [comment]
Idk why that was working locally but with the updated not ?

**Comment by sliepie** [comment]
It seems that the white version contains errors, see #12

**Comment by EQuimper** [comment]
You think we can touch the less files or that not gonna work ?

**Pull request merged**
