### PR TITLE
Atomv2

### PR DESCRIPTION
**Pull request by EQuimper**
Change the text color and add more italic

### CODE REVIEW

**Comment by sliepie** [comment]
Thanks for the changes, the customized version looks great! Based on the adjustments you've made, we have decided to create a new flavor of this theme, `Oceanic Next Italic -  White`.

I see you've edited the .less files of atom directly, unfortunately your changes are overwritten when we generate the atom version again, using the corresponding `tmTheme` file. Therefore I would like you to ask if you could make the changes to the `Oceanic Next Italic - White.tmTheme` file as well?

**Comment by EQuimper** [comment]
Yes I can do this sry if I make some mistake this is my first time a contribute to a project on github.

**Comment by sliepie** [comment]
You're welcome! :smiley: We're happily accepting your contributions!

**Comment by sliepie** [comment]
See #9 for merged result

**Pull request closed without merging**
